### ISSUE TITLE
Change State Name

### ISSUE THREAD

**Issue by aarrunyal** [sagautam5/local-states-nepal#21]
Please change Province 2 name to Madhesh Pradesh.

**Comment by sagautam5** [comment]
@aarrunyal Thank you so much for finding the issue in the province name. Is that name is official by now or still under the process to update in government level ?

**Comment by aarrunyal** [comment]
Hello Saugat,

It official name for province 2. You can change it to Madhesh Pradesh

**Comment by sagautam5** [comment]
@aarrunyal Province name has been updated !
https://github.com/sagautam5/local-states-nepal/commit/74fd2cba94386221cd7a61d7c5f3df2aa584ffc9

You can use master branch for now, and this change will be added on next release. Thank you so much for raising issue
