### ISSUE TITLE
Release new version with updated names

### ISSUE THREAD

**Issue by iamsubingyawali** [sagautam5/local-states-nepal#29]
It has been a while since the last version of this package was released, during which new province names have been added. I think a minor version update would be good.

**Comment by sagautam5** [comment]
@iamsubingyawali Thank your for your comment. I was working on some issues within this project. We will publish new version very soon.

**Comment by sagautam5** [comment]
@iamsubingyawali Thank you so much for your contribution in this open source repository, specially in [this release](https://github.com/sagautam5/local-states-nepal/releases/tag/v1.0.8)
